# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build effect-todo-app`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t effect-todo-app`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system effect-todo-app && \
          adduser --system -G effect-todo-app effect-todo-app

COPY dist/effect-todo-app effect-todo-app/
RUN chown -R effect-todo-app:effect-todo-app .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix effect-todo-app --omit=dev -f install

CMD [ "node", "effect-todo-app" ]
